/home/bahaduri/VIPER/lamorel/lamorel/src/lamorel_launcher/launch.py:15: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path='', config_name='')
/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Traceback (most recent call last):
  File "/home/bahaduri/VIPER/experiments/Train_dual_PPO.py", line 16, in <module>
    login("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")
  File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 31, in inner_f
    return f(*args, **kwargs)
  File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/huggingface_hub/_login.py", line 126, in login
    _login(token, add_to_git_credential=add_to_git_credential)
  File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/huggingface_hub/_login.py", line 412, in _login
    _set_active_token(token_name=token_name, add_to_git_credential=add_to_git_credential)
  File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/huggingface_hub/_login.py", line 457, in _set_active_token
    raise ValueError(f"Token {token_name} not found in {constants.HF_STORED_TOKENS_PATH}")
ValueError: Token model_load not found in /home/bahaduri/.cache/huggingface/stored_tokens
W0608 07:23:51.007058 140718768101184 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 2135597 closing signal SIGTERM
E0608 07:23:51.016461 140718768101184 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 1 (pid: 2135598) of binary: /home/bahaduri/.conda/envs/viper2/bin/python3
Error executing job with overrides: ['rl_script_args.path=/home/bahaduri/VIPER/experiments/Train_dual_PPO.py', 'rl_script_args.output_dir=.', 'lamorel_args.accelerate_args.machine_rank=0', 'lamorel_args.llm_args.model_path=meta-llama/Llama-3.2-1B-Instruct', 'lamorel_args.llm_args.model_type=causal', 'rl_script_args.seed=3', 'rl_script_args.number_envs=1', 'rl_script_args.task=[1]', 'rl_script_args.output_dir=/home/bahaduri/VIPER/outputs/ppo_llm_wIntrinsic_dual_pick', 'rl_script_args.intrinsic_reward=True', 'lamorel_args.config_alfred=/home/bahaduri/VIPER/alfworld/configs/base_config.yaml', 'wandb_args.run=Examine_in_light', 'lamorel_args.llm_args.vlm_model_path=microsoft/Florence-2-base-ft', 'wandb_args.mode=offline', 'lamorel_args.distributed_setup_args.n_llm_processes=1', 'rl_script_args.transitions_buffer_len=5', 'rl_script_args.epochs=500', 'rl_script_args.gradient_batch_size=2', 'rl_script_args.name_environment=AlfredThorEnv', 'rl_script_args.startepochs=83']
Traceback (most recent call last):
  File "/home/bahaduri/VIPER/lamorel/lamorel/src/lamorel_launcher/launch.py", line 46, in main
    launch_command(accelerate_args)
  File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1204, in launch_command
    multi_gpu_launcher(args)
  File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/accelerate/commands/launch.py", line 825, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/bahaduri/VIPER/experiments/Train_dual_PPO.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-08_07:23:51
  host      : kavinsky
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2135598)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
